import { configSchema, type DbcConfig } from "./protocol";

export type LaunchStack = "Compounding Liquidity DAMM v2 Pool" | "Dynamic AMM v2 (DAMM v2 Locked LP)" | "DLMM Concentrated Bin Routing";
export type VenueTag = "xStocks Catalog" | "Backpack Onchain" | "Ondo RFQ" | "Jupiter LFG" | "Meteora Native";
export type Preset = DbcConfig & { id: string; ticker: string; description: string; risk: "LOW" | "MODERATE" | "HIGH"; featured?: boolean; venue: VenueTag; mechanics: string[]; stackTarget: LaunchStack };
type PresetCore = DbcConfig & { id: string; ticker: string; description: string; risk: "LOW" | "MODERATE" | "HIGH"; featured?: boolean };
const rows: PresetCore[] = [
  { id: "xstock-orderly", ticker: "XSTK", name: "xStock Orderly Open", description: "Controlled price discovery for tokenized equities with a long graduation runway.", assetClass: "Equity / xStocks", curve: "Stepped Institutional", quoteToken: "USDC", initialVirtualQuoteReserve: 18000, initialVirtualBaseReserve: 900000, graduationThreshold: 25000, startFeeBps: 120, endFeeBps: 25, feeDecaySlots: 1200, feeCliffSlots: 100, creatorFeeShareBps: 800, partnerFeeShareBps: 1200, protocolFeeShareBps: 1200, migrationFeeOption: 0, lockedLpBps: 9000, lpVestingDays: 365, risk: "LOW", featured: true },
  { id: "xstock-flat", ticker: "EQTY", name: "Equity Flat Entry", description: "A shallow entry ramp for stock pairs that prioritize predictable execution.", assetClass: "Equity / xStocks", curve: "Flat", quoteToken: "USDC", initialVirtualQuoteReserve: 26000, initialVirtualBaseReserve: 1100000, graduationThreshold: 40000, startFeeBps: 90, endFeeBps: 25, feeDecaySlots: 1600, feeCliffSlots: 120, creatorFeeShareBps: 700, partnerFeeShareBps: 1300, protocolFeeShareBps: 1200, migrationFeeOption: 0, lockedLpBps: 9500, lpVestingDays: 540, risk: "LOW" },
  { id: "xstock-growth", ticker: "GROW", name: "Growth Equity Discovery", description: "Progressive repricing for higher volatility equity themes.", assetClass: "Equity / xStocks", curve: "Exponential", quoteToken: "USDC", initialVirtualQuoteReserve: 12000, initialVirtualBaseReserve: 700000, graduationThreshold: 15000, startFeeBps: 240, endFeeBps: 30, feeDecaySlots: 900, feeCliffSlots: 70, creatorFeeShareBps: 1000, partnerFeeShareBps: 1000, protocolFeeShareBps: 1200, migrationFeeOption: 1, lockedLpBps: 8500, lpVestingDays: 270, risk: "MODERATE" },
  { id: "rwa-treasury", ticker: "TBIL", name: "Treasury Pair Stable", description: "Tight pricing for tokenized bills and yield bearing collateral.", assetClass: "RWA Pairs", curve: "Flat", quoteToken: "USDC", initialVirtualQuoteReserve: 45000, initialVirtualBaseReserve: 3000000, graduationThreshold: 50000, startFeeBps: 80, endFeeBps: 25, feeDecaySlots: 1800, feeCliffSlots: 100, creatorFeeShareBps: 400, partnerFeeShareBps: 1600, protocolFeeShareBps: 1200, migrationFeeOption: 0, lockedLpBps: 10000, lpVestingDays: 730, risk: "LOW" },
  { id: "rwa-credit", ticker: "CRDT", name: "Private Credit Ladder", description: "Stepped liquidity for credit instruments with staged demand.", assetClass: "RWA Pairs", curve: "Stepped Institutional", quoteToken: "USDC", initialVirtualQuoteReserve: 32000, initialVirtualBaseReserve: 1600000, graduationThreshold: 30000, startFeeBps: 160, endFeeBps: 30, feeDecaySlots: 1300, feeCliffSlots: 120, creatorFeeShareBps: 600, partnerFeeShareBps: 1400, protocolFeeShareBps: 1200, migrationFeeOption: 1, lockedLpBps: 9500, lpVestingDays: 540, risk: "LOW" },
  { id: "rwa-met", ticker: "METR", name: "MET Ecosystem Pair", description: "MET quoted migration path with a deep virtual reserve buffer.", assetClass: "RWA Pairs", curve: "Long Curve", quoteToken: "MET", initialVirtualQuoteReserve: 4800, initialVirtualBaseReserve: 800000, graduationThreshold: 9000, startFeeBps: 220, endFeeBps: 100, feeDecaySlots: 1500, feeCliffSlots: 80, creatorFeeShareBps: 800, partnerFeeShareBps: 1200, protocolFeeShareBps: 1200, migrationFeeOption: 2, lockedLpBps: 9000, lpVestingDays: 365, risk: "MODERATE" },
  { id: "agent-long", ticker: "AGNT", name: "Agent Long Runway", description: "Long discovery window for autonomous agents and inference markets.", assetClass: "AI Agents", curve: "Long Curve", quoteToken: "SOL", initialVirtualQuoteReserve: 44, initialVirtualBaseReserve: 850000, graduationThreshold: 160, startFeeBps: 500, endFeeBps: 100, feeDecaySlots: 1000, feeCliffSlots: 50, creatorFeeShareBps: 1600, partnerFeeShareBps: 600, protocolFeeShareBps: 1200, migrationFeeOption: 2, lockedLpBps: 8000, lpVestingDays: 180, risk: "MODERATE", featured: true },
  { id: "agent-jup", ticker: "JAI", name: "JUP Agent Network", description: "JUP quoted agent launches with a measured early fee decay.", assetClass: "AI Agents", curve: "Exponential", quoteToken: "JUP", initialVirtualQuoteReserve: 2500, initialVirtualBaseReserve: 950000, graduationThreshold: 6500, startFeeBps: 400, endFeeBps: 100, feeDecaySlots: 800, feeCliffSlots: 45, creatorFeeShareBps: 1500, partnerFeeShareBps: 700, protocolFeeShareBps: 1200, migrationFeeOption: 2, lockedLpBps: 8000, lpVestingDays: 180, risk: "MODERATE" },
  { id: "agent-compute", ticker: "COMP", name: "Compute Sprint", description: "Faster migration for compute collectives seeking rapid liquidity.", assetClass: "AI Agents", curve: "Exponential", quoteToken: "JupUSD", initialVirtualQuoteReserve: 2500, initialVirtualBaseReserve: 650000, graduationThreshold: 8000, startFeeBps: 650, endFeeBps: 200, feeDecaySlots: 500, feeCliffSlots: 30, creatorFeeShareBps: 1700, partnerFeeShareBps: 500, protocolFeeShareBps: 1200, migrationFeeOption: 3, lockedLpBps: 7000, lpVestingDays: 120, risk: "HIGH" },
  { id: "meme-conviction", ticker: "CNVC", name: "Conviction Builder", description: "Anti-snipe cliff and gradual price discovery for community launches.", assetClass: "Conviction / Meme", curve: "Long Curve", quoteToken: "SOL", initialVirtualQuoteReserve: 28, initialVirtualBaseReserve: 1000000, graduationThreshold: 120, startFeeBps: 800, endFeeBps: 200, feeDecaySlots: 700, feeCliffSlots: 45, creatorFeeShareBps: 1800, partnerFeeShareBps: 500, protocolFeeShareBps: 1200, migrationFeeOption: 3, lockedLpBps: 7500, lpVestingDays: 90, risk: "HIGH" },
  { id: "meme-fast", ticker: "FST", name: "Fast Lane", description: "High initial protection and rapid graduation for high demand launches.", assetClass: "Conviction / Meme", curve: "Exponential", quoteToken: "SOL", initialVirtualQuoteReserve: 16, initialVirtualBaseReserve: 550000, graduationThreshold: 75, startFeeBps: 1200, endFeeBps: 400, feeDecaySlots: 350, feeCliffSlots: 25, creatorFeeShareBps: 2000, partnerFeeShareBps: 400, protocolFeeShareBps: 1200, migrationFeeOption: 4, lockedLpBps: 6000, lpVestingDays: 60, risk: "HIGH" },
  { id: "meme-community", ticker: "CMNT", name: "Community Anchor", description: "Deep JupUSD curve with a slower fee glide and extended LP lock.", assetClass: "Conviction / Meme", curve: "Stepped Institutional", quoteToken: "JupUSD", initialVirtualQuoteReserve: 3800, initialVirtualBaseReserve: 1200000, graduationThreshold: 12000, startFeeBps: 500, endFeeBps: 200, feeDecaySlots: 1200, feeCliffSlots: 80, creatorFeeShareBps: 1400, partnerFeeShareBps: 800, protocolFeeShareBps: 1200, migrationFeeOption: 3, lockedLpBps: 8500, lpVestingDays: 180, risk: "MODERATE" },
];

const metadata: Record<string, { venue: VenueTag; mechanics: string[]; stackTarget: LaunchStack }> = {
  "xstock-orderly": { venue: "xStocks Catalog", mechanics: ["Oracle GuardrailBand", "Market-Open Cliff Sync", "Compounding Fee Share"], stackTarget: "Compounding Liquidity DAMM v2 Pool" },
  "xstock-flat": { venue: "xStocks Catalog", mechanics: ["Market-Open Cliff Sync", "Oracle GuardrailBand"], stackTarget: "Dynamic AMM v2 (DAMM v2 Locked LP)" },
  "xstock-growth": { venue: "Backpack Onchain", mechanics: ["Oracle GuardrailBand", "Compounding Fee Share"], stackTarget: "DLMM Concentrated Bin Routing" },
  "rwa-treasury": { venue: "Ondo RFQ", mechanics: ["Oracle GuardrailBand", "Market-Open Cliff Sync"], stackTarget: "Compounding Liquidity DAMM v2 Pool" },
  "rwa-credit": { venue: "Ondo RFQ", mechanics: ["Oracle GuardrailBand", "Compounding Fee Share"], stackTarget: "Dynamic AMM v2 (DAMM v2 Locked LP)" },
  "rwa-met": { venue: "Meteora Native", mechanics: ["Compounding Fee Share", "Market-Open Cliff Sync"], stackTarget: "DLMM Concentrated Bin Routing" },
  "agent-long": { venue: "Backpack Onchain", mechanics: ["Compounding Fee Share", "Oracle GuardrailBand"], stackTarget: "Compounding Liquidity DAMM v2 Pool" },
  "agent-jup": { venue: "Jupiter LFG", mechanics: ["Market-Open Cliff Sync", "Compounding Fee Share"], stackTarget: "DLMM Concentrated Bin Routing" },
  "agent-compute": { venue: "Jupiter LFG", mechanics: ["Compounding Fee Share"], stackTarget: "Dynamic AMM v2 (DAMM v2 Locked LP)" },
  "meme-conviction": { venue: "Meteora Native", mechanics: ["Market-Open Cliff Sync", "Compounding Fee Share"], stackTarget: "Dynamic AMM v2 (DAMM v2 Locked LP)" },
  "meme-fast": { venue: "Jupiter LFG", mechanics: ["Oracle GuardrailBand"], stackTarget: "DLMM Concentrated Bin Routing" },
  "meme-community": { venue: "Meteora Native", mechanics: ["Compounding Fee Share", "Oracle GuardrailBand"], stackTarget: "Compounding Liquidity DAMM v2 Pool" },
};

export const PRESETS: Preset[] = rows.map((preset) => ({ ...configSchema.parse(preset), id: preset.id, ticker: preset.ticker, description: preset.description, risk: preset.risk, featured: preset.featured, ...metadata[preset.id] }));
export const ASSET_CLASSES = ["All Strategies", "Equity / xStocks", "RWA Pairs", "AI Agents", "Conviction / Meme"] as const;

export function findPresets(query: string, assetClass: string): Preset[] {
  const normalized = query.trim().toLowerCase();
  return PRESETS.filter((preset) => (assetClass === "All Strategies" || preset.assetClass === assetClass) && (!normalized || [preset.name, preset.ticker, preset.description, preset.curve, preset.quoteToken, preset.venue, preset.stackTarget, ...preset.mechanics].some((field) => field.toLowerCase().includes(normalized))));
}
